const dataMain =
[
    {
      "serialNumber": 1,
      "phoneNumber": "1234567890",
      "email": "john.doe@example.com",
      "whatsappNumber": "1234567890",
      "address": "123 Main Street",
      "city": "New York",
      "state": "NY",
      "country": "USA",
      "pincode": "10001",
      "occupation": "Sales Manager",
      "typeOfWork": "Sales",
      "monthlyIncome": "$5000",
      "companyName": "ABC Inc.",
      "product": "Widgets",
      "productCompany": "Widget Corp",
      "plan": "Premium",
      "name": "John Doe",
      "date": "09-03-2024",
      "status": "Meetings Pending",
      "clientStatus": "Mandate Approved",
      "taskStatus": "Inform Client"
    },
    {
      "serialNumber": 2,
      "phoneNumber": "1234567890",
      "email": "jane.smith@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Elm Street",
      "city": "Los Angeles",
      "state": "CA",
      "country": "USA",
      "pincode": "90001",
      "occupation": "Software Engineer",
      "typeOfWork": "Technology",
      "monthlyIncome": "$6000",
      "companyName": "XYZ Tech",
      "product": "Software",
      "productCompany": "XYZ Tech",
      "plan": "Enterprise",
      "name": "Jane Smith",
      "date": "09-03-2024",
      "status": "Leads Lost",
      "clientStatus": "Insurance Under Process",
      "taskStatus": "Under Process"
    },
    {
      "serialNumber": 3,
      "phoneNumber": "1234567890",
      "email": "michael.johnson@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Oak Street",
      "city": "Chicago",
      "state": "IL",
      "country": "USA",
      "pincode": "60601",
      "occupation": "Teacher",
      "typeOfWork": "Education",
      "monthlyIncome": "$4000",
      "companyName": "Local School",
      "product": "Education Services",
      "productCompany": "Local School",
      "plan": "Basic",
      "name": "Michael Johnson",
      "date": "09-03-2024",
      "status": "Leads Win",
      "clientStatus": "Demat Under Process",
      "taskStatus": "Mandate Pending"
    },
    {
      "serialNumber": 4,
      "phoneNumber": "1234567890",
      "email": "emily.williams@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Pine Street",
      "city": "San Francisco",
      "state": "CA",
      "country": "USA",
      "pincode": "94101",
      "occupation": "Doctor",
      "typeOfWork": "Healthcare",
      "monthlyIncome": "$8000",
      "companyName": "General Hospital",
      "product": "Medical Services",
      "productCompany": "General Hospital",
      "plan": "Premium Plus",
      "name": "Emily Williams",
      "date": "09-03-2024",
      "status": "Meetings Schedule",
      "clientStatus": "Mandate Pending",
      "taskStatus": "Task Complete"
    },
    {
      "serialNumber": 5,
      "phoneNumber": "1234567890",
      "email": "daniel.brown@example.com",
      "whatsappNumber": "1234567890",
      "address": "321 Maple Street",
      "city": "Boston",
      "state": "MA",
      "country": "USA",
      "pincode": "02101",
      "occupation": "Freelancer",
      "typeOfWork": "Consulting",
      "monthlyIncome": "$7000",
      "companyName": "Self-Employed",
      "product": "Consulting Services",
      "productCompany": "Self-Employed",
      "plan": "Hourly",
      "name": "Daniel Brown",
      "date": "09-03-2024",
      "status": "Follow up",
      "clientStatus": "Case Decline",
      "taskStatus": "Reject"
    },
    {
      "serialNumber": 6,
      "phoneNumber": "1234567890",
      "email": "olivia.jones@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Cedar Street",
      "city": "Seattle",
      "state": "WA",
      "country": "USA",
      "pincode": "98101",
      "occupation": "Accountant",
      "typeOfWork": "Finance",
      "monthlyIncome": "$5500",
      "companyName": "Financial Firm",
      "product": "Financial Services",
      "productCompany": "Financial Firm",
      "plan": "Gold",
      "name": "Olivia Jones",
      "date": "09-03-2024",
      "status": "Meetings Pending",
      "clientStatus": "Reject",
      "taskStatus": "Waiting For Documents"
    },
    {
      "serialNumber": 7,
      "phoneNumber": "1234567890",
      "email": "william.garcia@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Walnut Street",
      "city": "Miami",
      "state": "FL",
      "country": "USA",
      "pincode": "33101",
      "occupation": "Engineer",
      "typeOfWork": "Engineering",
      "monthlyIncome": "$6500",
      "companyName": "Tech Inc.",
      "product": "Engineering Services",
      "productCompany": "Tech Inc.",
      "plan": "Silver",
      "name": "William Garcia",
      "date": "09-03-2024",
      "status": "Leads Lost",
      "clientStatus": "Payment Pending",
      "taskStatus": "Under Process"
    },
    {
      "serialNumber": 8,
      "phoneNumber": "1234567890",
      "email": "sophia.martinez@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Oak Street",
      "city": "Austin",
      "state": "TX",
      "country": "USA",
      "pincode": "78701",
      "occupation": "Designer",
      "typeOfWork": "Design",
      "monthlyIncome": "$6000",
      "companyName": "Design Studio",
      "product": "Design Services",
      "productCompany": "Design Studio",
      "plan": "Basic",
      "name": "Sophia Martinez",
      "date": "09-03-2024",
      "status": "Leads Win",
      "clientStatus": "Task Completed",
      "taskStatus": "Task Complete"
    },
    {
      "serialNumber": 9,
      "phoneNumber": "1234567890",
      "email": "alexander.taylor@example.com",
      "whatsappNumber": "1234567890",
      "address": "123 Walnut Street",
      "city": "Denver",
      "state": "CO",
      "country": "USA",
      "pincode": "80201",
      "occupation": "Writer",
      "typeOfWork": "Writing",
      "monthlyIncome": "$4500",
      "companyName": "Publishing House",
      "product": "Books",
      "productCompany": "Publishing House",
      "plan": "Best Seller",
      "name": "Alexander Taylor",
      "date": "09-03-2024",
      "status": "Meetings Schedule",
      "clientStatus": "Document Recieved \nand Under Process",
      "taskStatus": "Inform Client"
    },
    {
      "serialNumber": 10,
      "phoneNumber": "1234567890",
      "email": "isabella.hernandez@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Maple Street",
      "city": "Portland",
      "state": "OR",
      "country": "USA",
      "pincode": "97201",
      "occupation": "Chef",
      "typeOfWork": "Hospitality",
      "monthlyIncome": "$5000",
      "companyName": "Restaurant",
      "product": "Food",
      "productCompany": "Restaurant",
      "plan": "Menu",
      "name": "Isabella Hernandez",
      "date": "09-03-2024",
      "status": "Follow up",
      "clientStatus": "Policy Issue",
      "taskStatus": "Under Process"
    },
    {
      "serialNumber": 11,
      "phoneNumber": "1234567890",
      "email": "james.adams@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Cedar Street",
      "city": "Houston",
      "state": "TX",
      "country": "USA",
      "pincode": "77001",
      "occupation": "Artist",
      "typeOfWork": "Art",
      "monthlyIncome": "$4000",
      "companyName": "Art Gallery",
      "product": "Artwork",
      "productCompany": "Art Gallery",
      "plan": "Exhibition",
      "name": "James Adams",
      "date": "09-03-2024",
      "status": "Meetings Pending",
      "clientStatus": "Insurance Pending",
      "taskStatus": "Mandate Pending"
    },
    {
      "serialNumber": 12,
      "phoneNumber": "1234567890",
      "email": "amelia.young@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Pine Street",
      "city": "San Francisco",
      "state": "CA",
      "country": "USA",
      "pincode": "94101",
      "occupation": "Musician",
      "typeOfWork": "Music",
      "monthlyIncome": "$3500",
      "companyName": "Band",
      "product": "Music",
      "productCompany": "Band",
      "plan": "Gigs",
      "name": "Amelia Young",
      "date": "09-03-2024",
      "status": "Leads Lost",
      "clientStatus": "Waiting For Documents",
      "taskStatus": "Task Complete"
    },
    {
      "serialNumber": 13,
      "phoneNumber": "1234567890",
      "email": "benjamin.wilson@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Elm Street",
      "city": "Boston",
      "state": "MA",
      "country": "USA",
      "pincode": "02101",
      "occupation": "Athlete",
      "typeOfWork": "Sports",
      "monthlyIncome": "$7000",
      "companyName": "Sports Team",
      "product": "Sports",
      "productCompany": "Sports Team",
      "plan": "Professional",
      "name": "Benjamin Wilson",
      "date": "09-03-2024",
      "status": "Leads Win",
      "clientStatus": "Conversation Pending",
      "taskStatus": "Waiting For Documents"
    },
    {
      "serialNumber": 14,
      "phoneNumber": "1234567890",
      "email": "mia.lee@example.com",
      "whatsappNumber": "1234567890",
      "address": "123 Oak Street",
      "city": "Austin",
      "state": "TX",
      "country": "USA",
      "pincode": "78701",
      "occupation": "Photographer",
      "typeOfWork": "Photography",
      "monthlyIncome": "$4500",
      "companyName": "Photography Studio",
      "product": "Photography",
      "productCompany": "Photography Studio",
      "plan": "Premium",
      "name": "Mia Lee",
      "date": "09-03-2024",
      "status": "Meetings Schedule",
      "clientStatus": "Under Process",
      "taskStatus": "Reject"
    },
    {
      "serialNumber": 15,
      "phoneNumber": "1234567890",
      "email": "ethan.anderson@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Maple Street",
      "city": "Portland",
      "state": "OR",
      "country": "USA",
      "pincode": "97201",
      "occupation": "Lawyer",
      "typeOfWork": "Legal",
      "monthlyIncome": "$9000",
      "companyName": "Law Firm",
      "product": "Legal Services",
      "productCompany": "Law Firm",
      "plan": "Retainer",
      "name": "Ethan Anderson",
      "date": "09-03-2024",
      "status": "Follow up",
      "clientStatus": "Waiting For Documents",
      "taskStatus": "Task Complete"
    },
    {
      "serialNumber": 16,
      "phoneNumber": "1234567890",
      "email": "charlotte.gonzalez@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Pine Street",
      "city": "San Francisco",
      "state": "CA",
      "country": "USA",
      "pincode": "94101",
      "occupation": "Consultant",
      "typeOfWork": "Consulting",
      "monthlyIncome": "$7500",
      "companyName": "Consulting Firm",
      "product": "Consulting Services",
      "productCompany": "Consulting Firm",
      "plan": "Hourly",
      "name": "Charlotte Gonzalez",
      "date": "09-03-2024",
      "status": "Meetings Pending",
      "clientStatus": "Under Process",
      "taskStatus": "Under Process"
    },
    {
      "serialNumber": 17,
      "phoneNumber": "1234567890",
      "email": "jacob.rodriguez@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Elm Street",
      "city": "New York",
      "state": "NY",
      "country": "USA",
      "pincode": "10001",
      "occupation": "Manager",
      "typeOfWork": "Management",
      "monthlyIncome": "$8500",
      "companyName": "Management Company",
      "product": "Management Services",
      "productCompany": "Management Company",
      "plan": "Full Service",
      "name": "Jacob Rodriguez",
      "date": "09-03-2024",
      "status": "Leads Lost",
      "clientStatus": "Mandate Pending",
      "taskStatus": "Waiting For Documents"
    },
    {
      "serialNumber": 18,
      "phoneNumber": "1234567890",
      "email": "ava.martinez@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Oak Street",
      "city": "Austin",
      "state": "TX",
      "country": "USA",
      "pincode": "78701",
      "occupation": "CEO",
      "typeOfWork": "Business",
      "monthlyIncome": "$10000",
      "companyName": "Tech Startup",
      "product": "Technology",
      "productCompany": "Tech Startup",
      "plan": "Startup",
      "name": "Ava Martinez",
      "date": "09-03-2024",
      "status": "Leads Win",
      "clientStatus": "Case Decline",
      "taskStatus": "Reject"
    },
    {
      "serialNumber": 19,
      "phoneNumber": "1234567890",
      "email": "logan.perez@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Walnut Street",
      "city": "Chicago",
      "state": "IL",
      "country": "USA",
      "pincode": "60601",
      "occupation": "Developer",
      "typeOfWork": "Technology",
      "monthlyIncome": "$8500",
      "companyName": "Tech Company",
      "product": "Technology",
      "productCompany": "Tech Company",
      "plan": "Premium",
      "name": "Logan Perez",
      "date": "09-03-2024",
      "status": "Meetings Schedule",
      "clientStatus": "Reject",
      "taskStatus": "Inform Client"
    },
    {
      "serialNumber": 20,
      "phoneNumber": "1234567890",
      "email": "sofia.king@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Cedar Street",
      "city": "Seattle",
      "state": "WA",
      "country": "USA",
      "pincode": "98101",
      "occupation": "Real Estate Agent",
      "typeOfWork": "Real Estate",
      "monthlyIncome": "$7500",
      "companyName": "Real Estate Agency",
      "product": "Property",
      "productCompany": "Real Estate Agency",
      "plan": "Standard",
      "name": "Sofia King",
      "date": "09-03-2024",
      "status": "Follow up",
      "clientStatus": "Task Completed",
      "taskStatus": "Task Complete"
    },
    {
      "serialNumber": 21,
      "phoneNumber": "1234567890",
      "email": "james.adams@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Elm Street",
      "city": "Los Angeles",
      "state": "CA",
      "country": "USA",
      "pincode": "90001",
      "occupation": "Actor",
      "typeOfWork": "Entertainment",
      "monthlyIncome": "$5500",
      "companyName": "Film Studio",
      "product": "Films",
      "productCompany": "Film Studio",
      "plan": "Blockbuster",
      "name": "James Adams",
      "date": "09-03-2024",
      "status": "Meetings Pending",
      "clientStatus": "Mandate Approved",
      "taskStatus": "Inform Client"
    },
    {
      "serialNumber": 22,
      "phoneNumber": "1234567890",
      "email": "amelia.young@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Oak Street",
      "city": "Chicago",
      "state": "IL",
      "country": "USA",
      "pincode": "60601",
      "occupation": "Interior Designer",
      "typeOfWork": "Design",
      "monthlyIncome": "$6000",
      "companyName": "Design Studio",
      "product": "Interior Design",
      "productCompany": "Design Studio",
      "plan": "Custom",
      "name": "Amelia Young",
      "date": "09-03-2024",
      "status": "Leads Lost",
      "clientStatus": "Payment Pending",
      "taskStatus": "Waiting For Documents"
    },
    {
      "serialNumber": 23,
      "phoneNumber": "1234567890",
      "email": "benjamin.morris@example.com",
      "whatsappNumber": "1234567890",
      "address": "101 Pine Street",
      "city": "San Francisco",
      "state": "CA",
      "country": "USA",
      "pincode": "94101",
      "occupation": "Journalist",
      "typeOfWork": "Media",
      "monthlyIncome": "$5000",
      "companyName": "News Agency",
      "product": "News",
      "productCompany": "News Agency",
      "plan": "Subscription",
      "name": "Benjamin Morris",
      "date": "09-03-2024",
      "status": "Follow up",
      "clientStatus": "Under Process",
      "taskStatus": "Reject"
    },
    {
      "serialNumber": 24,
      "phoneNumber": "1234567890",
      "email": "lucy.nguyen@example.com",
      "whatsappNumber": "1234567890",
      "address": "456 Maple Street",
      "city": "Portland",
      "state": "OR",
      "country": "USA",
      "pincode": "97201",
      "occupation": "Dentist",
      "typeOfWork": "Healthcare",
      "monthlyIncome": "$7500",
      "companyName": "Dental Clinic",
      "product": "Dental Services",
      "productCompany": "Dental Clinic",
      "plan": "Premium",
      "name": "Lucy Nguyen",
      "date": "09-03-2024",
      "status": "Meetings Schedule",
      "clientStatus": "Insurance Under Process",
      "taskStatus": "Inform Client"
    },
    {
      "serialNumber": 25,
      "phoneNumber": "1234567890",
      "email": "ryan.hall@example.com",
      "whatsappNumber": "1234567890",
      "address": "789 Elm Street",
      "city": "Boston",
      "state": "MA",
      "country": "USA",
      "pincode": "02101",
      "occupation": "Pilot",
      "typeOfWork": "Aviation",
      "monthlyIncome": "$9000",
      "companyName": "Airline",
      "product": "Flights",
      "productCompany": "Airline",
      "plan": "Business Class",
      "name": "Ryan Hall",
      "date": "09-03-2024",
      "status": "Leads Win",
      "clientStatus": "Demat Under Process",
      "taskStatus": "Mandate Pending"
    }
  ];
export default dataMain;

